# Generated by Django 4.2.8 on 2024-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_alter_dish_name_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='aggregate_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='rating_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
