# Generated by Django 4.2.8 on 2024-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_dish_aggregate_rating_dish_rating_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='aggregate_rating',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='rating_text',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='aggregate_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
